spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i4d110.p.ssafy.io:3307/yacht?characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  #  mvc:
  #    static-path-pattern: ../../../bulid/src/main/resources/static/**
  # email 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: taejin0323@gmail.com
    password: aywnfrboyfiazcpn
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    # 소셜 로그인(google)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995943247986-pv1vngmuqeelfuehe8pinbo9brlurc91.apps.googleusercontent.com
            client-secret: 3LeJfOF-5YwUXODhEvN86s0U
            scope: profile, email

# JWT 속성
yacht:
  app:
    jwtSecret: yachtSecretKey
    jwtExpirationMs: 86400000
    domain: https://i4d110.p.ssafy.io
    FileSubSrc: https://i4d110.p.ssafy.io/subImg/
    FileMainSrc: https://i4d110.p.ssafy.io/mainImg/
    paycode: 654e054049757a0cceb1fa50dffd3026
  # jwtExpirationMs 만료시간
  # jwtSecret : 비번
